swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - url: http://localhost:8080/api
    description: Servidor de Desenvolvimento
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /beneficiarios/cadastro:
    post:
      summary: Cadastrar um beneficiário
      operationId: cadastrarBeneficiario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Beneficiario'
      responses:
        '200':
          description: Beneficiário cadastrado com sucesso
        '400':
          description: Requisição inválida
  /beneficiarios/listar:
    get:
      summary: Listar todos os beneficiários
      operationId: listarBeneficiarios
      responses:
        '200':
          description: Lista de beneficiários recuperada com sucesso
        '404':
          description: Nenhum beneficiário encontrado
components:
  schemas:
    Beneficiario:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do beneficiário
        nome:
          type: string
          description: Nome do beneficiário
        idade:
          type: integer
          description: Idade do beneficiário
